let Operation = {
    0: "none",
    1: "dapai",
    2: "eat",
    3: "peng",
    4: "an_gang",
    5: "ming_gang",
    6: "add_gang",
    7: "liqi",
    8: "zimo",
    9: "rong",
    10: "jiuzhongjiupai",
    11: "babei",
    add_gang: 6,
    an_gang: 4,
    babei: 11,
    dapai: 1,
    eat: 2,
    jiuzhongjiupai: 10,
    liqi: 7,
    ming_gang: 5,
    none: 0,
    peng: 3,
    rong: 9,
    zimo: 8,
}

module.exports = Operation;